### ISSUE TITLE
DOI scraping may result in dataset instance while it is an article

### ISSUE THREAD

**Issue by fnielsen** [citation-js/citation-js#163] opened 2022-06-08 12:25 UTC
[10.1126/SCIENCE.ADD1068](https://doi.org/10.1126/SCIENCE.ADD1068) yield instance of Q1172284

See https://www.wikidata.org/w/index.php?title=Q112116175&action=history

This resulted in a error using Scholia, see https://github.com/WDscholia/scholia/issues/1981

**Expected behavior**
I would have expected instance of, e.g., Q570759

**Comment by larsgw** [comment] 2022-06-10 08:03
This seems to be an issue in the Crossref data, the API returns an item of type dataset:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<doi_records>
  <doi_record owner="10.1126" timestamp="2022-06-03 14:51:11">
    <crossref>
      <database>
        <database_metadata language="en">
          <titles>
            <title>AAAS Articles DO Group</title>
          </titles>
        </database_metadata>
        <dataset dataset_type="other">
          <titles>
            <title>Monkeypox outbreak questions intensify as cases soar</title>
          </titles>
          <database_date>
            <publication_date media_type="online">
              <month>05</month>
              <day>20</day>
              <year>2022</year>
            </publication_date>
          </database_date>
          <format>article</format>
          <doi_data>
            <doi>10.1126/science.add1068</doi>
            <resource>https://www.science.org/content/article/monkeypox-outbreak-questions-intensify-cases-soar</resource>
          </doi_data>
        </dataset>
      </database>
    </crossref>
  </doi_record>
</doi_records>
```

Compare with a journal article:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<doi_records>
  <doi_record owner="10.1093" timestamp="2019-01-11 10:04:19">
    <crossref>
      <journal>
        <journal_metadata language="en">
          <full_title>BioScience</full_title>
          <abbrev_title>BioScience</abbrev_title>
          <issn media_type="print">0006-3568</issn>
        </journal_metadata>
        <journal_issue>
          <publication_date media_type="print">
            <year>2006</year>
          </publication_date>
          <journal_volume>
            <volume>56</volume>
          </journal_volume>
          <issue>4</issue>
        </journal_issue>
        <journal_article publication_type="full_text">
          <titles>
            <title>The Economic Value of Ecological Services Provided by Insects</title>
          </titles>
          <!-- ... -->
        </journal_article>
      </journal>
    </crossref>
  </doi_record>
</doi_records>
```

You can see the same in the search results on Crossref: https://search.crossref.org/?from_ui=yes&q=10.1126/SCIENCE.ADD1068

![Screenshot_20220610_100127](https://user-images.githubusercontent.com/14018963/173019762-df66cb0e-c770-4762-bcc3-9cf659472267.png)

This seems to be happening for more articles: https://search.crossref.org/?q=AAAS+Articles+DO+Group&from_ui=yes

Not sure how much I can do about this myself, I could try to patch the data from this specific group of articles but I'd rather have that the data is fixed in Crossref.

**Comment by larsgw** [comment] 2022-06-10 08:11
This seems to affect 1,879,828 articles. The publication date seems to be wrong as well for all articles before October 2021.

**Comment by fnielsen** [comment] 2022-06-10 08:26
https://community.crossref.org/t/science-news-articles-are-labeled-dataset/2741

**Comment by fnielsen** [comment] 2022-06-10 08:26
https://community.crossref.org/t/science-news-articles-are-labeled-dataset/2741

**Comment by larsgw** [comment] 2022-06-10 11:25
I had also tweeted to Science because I suspect the cause is the data they send to Crossref (but I'm not sure): https://twitter.com/larswillighagen/status/1535172471598596096

**Comment by larsgw** [comment] 2024-01-22 19:42
Nothing Citation.js can do here, realistically. I don't think there's enough information in the metadata to reliably tell that it's not actually a dataset.

**Closed** 2024-01-22 19:42 UTC
Labels: package: plugin-doi
